---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: alpine
  environment:
    ES_URL: http://database:9200
  commands:
  - apk add curl bash
  - sleep 15
  - ./api.test.sh

services:
- name: database
  image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
  environment:
    discovery.type: single-node
  ports:
  - 9200

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
- name: test
  image: alpine
  environment:
    ES_URL: http://database:9200
  commands:
  - apk add curl bash
  - sleep 15
  - ./api.test.sh

- name: gh-pages
  image: plugins/gh-pages
  environment:
    PLUGIN_USER_NAME: Alexander Alexandrov
    PLUGIN_USER_EMAIL: aalexandrovv@gmail.com
  settings:
    username: redneckz
    password:
      from_secret: github_password

services:
- name: database
  image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
  environment:
    discovery.type: single-node
  ports:
  - 9200

trigger:
  event:
    - tag
